### ISSUE TITLE
签名

### ISSUE THREAD

**Issue by aucker** [BugenZhao/NGA#3]
你好，请问这个签名apple id是必须要开发者账号才能编译吗

**Comment by BugenZhao** [comment]
个人账号也可以编译安装到自己的机器上，不过需要每7天重新签名安装一遍。

**Comment by aucker** [comment]
多谢大佬，大佬太强了

**Comment by BugenZhao** [comment]
现在已经上架TestFlight了，欢迎下载安装体验😁
